# Generated by Django 5.0.1 on 2024-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sds011_3659_2022',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
