# Generated by Django 5.0.1 on 2024-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dht22_3660_2022_lat_dht22_3660_2022_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DHT22_3660_2022',
            new_name='DHT22',
        ),
        migrations.RenameModel(
            old_name='SDS011_3659_2022',
            new_name='SDS011',
        ),
    ]
